### ISSUE TITLE
Log not picking up anything anymore

### ISSUE THREAD

**Issue by Muzzlela** [snoww/loa-logs#10]
Was working perfectly fine on 20/06/23 after update it stopped picking up any data.  I uninstalled and downloiaded v1.2.3 again and seems that doesn't work anymore either. I'm not using a vpn or anything.

**Comment by snoww** [comment]
yeah patch broke it.
i need to wait for upstream https://github.com/lost-ark-dev/meter-core to push their changes, then i can start updating

**Comment by Muzzlela** [comment]
Oh I see, I thought that would be case but just wanted to make sure. Anyway appreciate the work. Thanks!

**Comment by snoww** [comment]
meter updated
