### ISSUE TITLE
Logs are not viewable if my Bard is present

### ISSUE THREAD

**Issue by BombzGaming** [snoww/loa-logs#105]
The icon for the class is missing in the list of logs.
![image](https://github.com/user-attachments/assets/472a3efe-91ed-49f9-8877-4afdd3d9fe1e)

Attempting to open any of those logs puts the program in a no-input state with a blank screen except for the header.
![image](https://github.com/user-attachments/assets/06b939fe-1d7a-4e36-98e7-73662de82fe9)

**Comment by snoww** [comment]
send me your encounter log

**Comment by BombzGaming** [comment]
How do I do that?  I don't see an option for it.

**Comment by snoww** [comment]
dm me on discord
