### ISSUE TITLE
Missing LogSkillChart.svelte

### ISSUE THREAD

**Issue by anyduck** [snoww/loa-logs#107]
> [vite] Pre-transform error: Failed to resolve import "./LogSkillChart.svelte" from "src/lib/components/logs/LogDamageMeter.svelte". Does the file exist?

https://github.com/snoww/loa-logs/blame/caadab132c6b8010acb7091b1a1c85507d342e99/src/lib/components/logs/LogDamageMeter.svelte#L43

**Comment by snoww** [comment]
sorry forgot to add that file
