### ISSUE TITLE
Windows 11 issues while dragging the dps meter window

### ISSUE THREAD

**Issue by levioh** [snoww/loa-logs#12]
Holding the left mouse to drag and move the window of the dps meter causes performances issues , the window doesn't follow the cursor and you have this weird delay where the windows moves slowly like a snail and your cursor is invisible and you can't actually tell where the cursor is , making it a hassle for w11 users to move the window.

**Comment by snoww** [comment]
There is a section in the FAQ for this issue

https://github.com/snoww/loa-logs#faq
