### ISSUE TITLE
Bug with installer

### ISSUE THREAD

**Issue by raylee220** [snoww/loa-logs#131]
The latest versions of Meter have presented this error when installing.
![Screenshot_15](https://github.com/user-attachments/assets/b3bff2f3-7cd3-42ec-8777-4ba747d75222)

**Comment by envys7** [comment]
i have the sme issue too, i reinstalled and the logs still error

**Comment by yanllb** [comment]
Same and logs don't work

**Comment by aly68** [comment]
![image](https://github.com/user-attachments/assets/02b018b1-f5b0-4a52-9b6b-e2baeaa79458)
why did .sys still working even after lost ark and meter closed.  the url of the file scared me

**Comment by snoww** [comment]
read the announcement channel

the driver is in use so you can't remove it.

you can run the command in cmd with admin: `sc stop windivert`
