### ISSUE TITLE
Possibly directional % display bug

### ISSUE THREAD

**Issue by yamiM0NSTER** [snoww/loa-logs#16]
Hello,

I have recently started using this version of dps meter and noticed that for some reason it seems to be aggregating all of sources of damage in directional attack stats. What I mean by that is for some reason in overall display it will show for example 40% back attack:
![image](https://github.com/snoww/loa-logs/assets/22958062/3b319673-f72f-4fbd-8284-3101a10ec2e7)
However if we look at details skills/damage sources with back attack modifiers are at way higher percentage:
![image](https://github.com/snoww/loa-logs/assets/22958062/b327ac9d-9de0-4b11-8cb6-b736c3eaa064)

If that is intended then would like some clarification on that because in loa details it seems to only aggregate sources that have back attack modifier (idk about both front/back skills).

Cheers

**Comment by snoww** [comment]
front/back %s are calculated by the total # of hits that are front/back attacks divided by the total number of hits
im too lazy to rework it to only count attacks that have positional mods

**Comment by snoww** [comment]
added option to show back/front % as % of dmg instead of hits
