### ISSUE TITLE
Shortcut Show/Hide Meter bugs the window (minor)

### ISSUE THREAD

**Issue by safteinzz** [snoww/loa-logs#22]
If you press the shortcut to hide/show 2 times (hide-> show) when not in game or when you for example go to desktop then to the game, and you think okay dps meter is not showing maybe I have hidden it and you press it 2 times, the meter window falls into bug.

The window of the meter will show like this in alt+tab, but you will have no way to show it, reescale or anything  (only solution is restart):

![image](https://github.com/snoww/loa-logs/assets/49436581/e108834a-bb0a-4e98-b65b-12b72e6e8914)

I will use this issue to mark that, minimizing and just making the window super small with a expand button instead of always going to tray would be appreciated.

**Comment by snoww** [comment]
huh, does this happen often? you cant drag the corners/double click to fix the window size?
using the shortcut doesnt do this for me

**Comment by safteinzz** [comment]
> does this happen often?

Yes, I can make this happen anytime.


> you cant drag the corners/double click to fix the window size?

Even though it appears there, the window is just hidden. You cannot tab to it.

> using the shortcut doesnt do this for me

Try following this:

1. Open game
3. Open LOA LOGS
4. Windows + D (go desktop)
5. Open game window
6. Shortcut to hide
7. Shortcut to show
8. Window should be bugged


---

My game is on borderless btw. 

Thanks for the support

**Comment by snoww** [comment]
hmm I tried your repro steps and couldn't get my window to be like that. 
when the window is not bugged, try making it bigger. I think it might be because you are somehow making the window smaller than the minimum allowed, thus bugging it out.

**Comment by safteinzz** [comment]
https://www.youtube.com/watch?v=DkA6Taw9TwU

So you can see

Timestamps:

1. Open game (already open)
2. Open LOA LOGS (0:08)
3. Windows + D (0:14)
4. Open game window (0:15)
5. Shortcut to hide (0:18)
6. Shortcut to show (0:18)
7. Window should be bugged (0:19)

**Comment by snoww** [comment]
ah i reproduced it, although i don't know how to fix it, need to investigate

**Comment by snoww** [comment]
although not fixed, i have implemented a workaround with 3 new context menus in the system tray. that allows saveing/loading/resetting of the meter window. hopefully this is a comparable alternative.
