### ISSUE TITLE
Suggestions: total person DPS and DPS chart boss HP bar #

### ISSUE THREAD

**Issue by iwllyu** [snoww/loa-logs#26]
Thanks for the hard work - the app is great and very responsive

I have two minor suggestions:

1. It would be great if on the skill breakdown screen it will display the total DPS somewhere. I know it says total DPS on the previous screen where it shows all the players, but having it on the skill breakdown screen would be useful when sharing it. The "Total DPS" currently listed is the Raid's DPS (it doesn't change when clicking into a specific player)
<img width="509" alt="image" src="https://github.com/snoww/loa-logs/assets/5480967/e67134fc-7c51-4188-8664-443f6b500d60">

3. In the DPS chart screen, it would be cool if we could see the number of bars a boss has instead of the percentage, so we can more easily correlate DPS with specific boss patterns/mechs
<img width="494" alt="Screenshot 2023-08-31 at 2 11 33 PM" src="https://github.com/snoww/loa-logs/assets/5480967/e379d4a2-e6e6-4879-9bdc-09dd7729a290">

**Comment by snoww** [comment]
added
