### ISSUE TITLE
dps meter stops collecting data randomly mid-fight

### ISSUE THREAD

**Issue by Quiksmage** [snoww/loa-logs#27]
I'm noticing that while running the meter in a VM dps will stop recording mid-fight. Loa details doesn't seem to have this issue, so I'm wondering what may be different. I only run in a vm so I can't confirm whether bare-metal would differ.

For instance, today I have a caliligos log that is only logged for 49 seconds, but lasted around 5 minutes.

The only thing i see mentioned in the log is a warning of dropped packets. it correctly starts getting new data when the next fight starts as well. Is there anywhere else I can look for clues as to why this is happening?
![image](https://github.com/snoww/loa-logs/assets/12449533/54eefdf2-7a91-4c12-8719-54b425cf910b)

Here's another example where it stopped showing new data past 79%
![image](https://github.com/snoww/loa-logs/assets/12449533/e7e57c1c-75e2-46a7-8529-5c14c370b20a)
when i go into the log itself, it shows the log only lasting 1:17 whereas you can see it was 6 minutes in the live data.
![image](https://github.com/snoww/loa-logs/assets/12449533/6f96197d-9f74-455b-8d6d-a48b66939d70)

**Comment by snoww** [comment]
what are your settings? do you use a vpn? do you have raw socket on?

**Comment by Quiksmage** [comment]
No VPN, I've tried raw  socket on and off, no difference.

Settings listed below:
![image](https://github.com/snoww/loa-logs/assets/12449533/092ad18f-2872-4c01-acd3-139e26b84458)
I've tried with auto network selection off and on, raw socket off and on. It still happens.
I've tried deleting everything and re-installing with no change as well.
I noticed that my settings still persist after uninstalling and deleting the local appdata folder. Are there any registry keys or files elsewhere I should delete?

The only other thing I haven't tried is setting up a new VM from scratch.

**Comment by snoww** [comment]
its probably a vm thing. I've had other people have similar issues where packets are dropping in vms. try running meter without it to see if you have any dropped packets. If you still do, then its probably your internet related.

**Comment by Quiksmage** [comment]
Is there a way that this meter detects network packets different from the original loa details? That meter doesn't have that issue at all.

**Comment by snoww** [comment]
yeah it uses a different packet sniffer in the backend

**Comment by Quiksmage** [comment]
I'll keep troubleshooting, trying different virtual nics and such.

**Comment by Quiksmage** [comment]
Changing NICs in virtualbox didn't seem to make an impact.

I set up  a vm in hyper-v
followed this guide for setting promiscuous mode on the nic:
https://learn.microsoft.com/en-us/azure/defender-for-iot/organizations/traffic-mirroring/configure-mirror-hyper-v

So far, I haven't had any dropped packets in the logs nor any freezes in the meter. I'll report back if the issue returns. if it doesn't, i'll consider this a workaround.

**Comment by Quiksmage** [comment]
I haven't had any issues under the hyper-v hypervisor, so I'll consider this closed.
