### ISSUE TITLE
Listen port

### ISSUE THREAD

**Issue by katyzzzzz** [snoww/loa-logs#3]
Hello, im using vpn and raw input doesnt work, Can you add listen port like on loadetails pls?
![image](https://user-images.githubusercontent.com/132819474/236673478-c78c79ee-3a7c-4108-a201-6593ddb06912.png)

**Comment by snoww** [comment]
added with [v1.1.10](https://github.com/snoww/loa-logs/releases/tag/v1.1.10)

**Comment by katyzzzzz** [comment]
big thx <3
