### ISSUE TITLE
Show/Hide Logs Shortcut only opens the logs

### ISSUE THREAD

**Issue by JonasHri** [snoww/loa-logs#30]
As the title sais, for me the shortcut is only able to open the logs window and another press does not close it but only reloads the window. The Show/Hide Meter opens and closes the meter as intended for me.

**Comment by snoww** [comment]
that is currently intended, is that something you’d like to have?

**Comment by JonasHri** [comment]
Yes, that would be great. I have the meter in the same location as the logs and I only want one of them open at a time. So having that shortcut would be quite nice for me.
