### ISSUE TITLE
meter is not recording

### ISSUE THREAD

**Issue by integrax3** [snoww/loa-logs#31]
hello. thank you for creating this.
after opening LOA logs as admin, going into raid, nothing seems to happen and would appreciate any help/advice

i have installed Npcap with WinPcap compatibilities
i have edgewebview2

i have also tried uninstall and reinstall from scratch

i have also try auto network selection and choosing manually/ also checking raw socket
is the port 6040 correct or does it need to be port that lost ark uses?

no issues with install/no errors

**Comment by snoww** [comment]
are you using VM or 1PC? wifi or ethernet?

**Comment by integrax3** [comment]
it is a VM, ethernet

both VM/PC are on the same ethernet adapter

thank you for the quick reply!

**Comment by snoww** [comment]
is the network adapter bridged + replicated on the VM?
otherwise im not too sure what the issue might be, my suggestion would be to just not run in a VM.

**Comment by integrax3** [comment]
thanks for the info, i was able to solve my problem. it ended up being hyperv bridge having an issue. virtualbox/vmware worked
