### ISSUE TITLE
Meter is not recording

### ISSUE THREAD

**Issue by dundon21** [snoww/loa-logs#34]
Hello current installed in my local machine when i tried to open the application it didnt show any error i did install the necessary files listed and meter is still not working. im currently using exitlog for the game not sure if it has something to do with that.

**Comment by VanStorm** [comment]
I don't run exitlag or anything like that, but the meter isn't recording anything for me either since today's update.
Probably something broke with the update.

**Comment by DSchab** [comment]
The meter always breaks with updates. It requires the maintainer to push a small patch. Nothing unusual
