### ISSUE TITLE
Feature Request: AP Buff % in damage view

### ISSUE THREAD

**Issue by Quiksmage** [snoww/loa-logs#35]
![image](https://github.com/snoww/loa-logs/assets/12449533/ddca145c-ca98-4314-880a-608be55c0e1f)

It'd be nice if either this was replaced with the values circled above or an additional option to have the % from above in the damage view. It would complement the brand % column.

![image](https://github.com/snoww/loa-logs/assets/12449533/5c452318-2ddc-424b-9613-8e9ff1554d0b)

**Comment by snoww** [comment]
uhhh, probably not... 
i will have to think about it, due to how atk pwr buff is calculated on-the-fly in the buff tab, and the buff % in the overview is pre-calculated

**Comment by Quiksmage** [comment]
would it not be similar to how the brand % one is calculated, but with different spell ids? I won't pretend to understand the back-end though :D

**Comment by snoww** [comment]
this is added in v1.2.39
