### ISSUE TITLE
Corrupted logs

### ISSUE THREAD

**Issue by SyadnomEtah** [snoww/loa-logs#37]
After recent patch/es there seems to be an issue with some of the logs becoming corrupted (noticed it mainly on Akkan and Kayangel raids). 

1. In class preview there seems to be an additional member "0" with missing icon
2. When trying to open said logs the app blanks out and nothing can be done until restart

I'm running on a single PC setup (Win 11) without VPN
![image](https://github.com/snoww/loa-logs/assets/23053462/47dc468e-5ccd-48b6-9200-95a7e9591a14)

**Comment by snoww** [comment]
should be fixed with latest patch, you can just delete those logs
