### ISSUE TITLE
buff% discreprancy

### ISSUE THREAD

**Issue by Quiksmage** [snoww/loa-logs#40]
There seems to be some differences in the buff % calculation between damage and party synergy tabs.

![image](https://github.com/snoww/loa-logs/assets/12449533/e6d81de9-d334-4803-9510-ff3e41656364)

![image](https://github.com/snoww/loa-logs/assets/12449533/6cb6bac7-4abe-4ca8-9eb3-fe6181594a21)

**Comment by snoww** [comment]
yeah because it also includes aura/moonfall/serenade
