### ISSUE TITLE
Meter sometimes doesn't track my party's brand/buff uptime

### ISSUE THREAD

**Issue by unicornInk** [snoww/loa-logs#41]
Intermittent issue, not sure what causes it. Brand/Buff% in overall view is 0% for party mates. Party Synergy view shows only 7 players, despite recording damage/casts of my character:

![image](https://github.com/snoww/loa-logs/assets/71574877/4e09109f-192e-4b6c-9e86-47b85ed0388b)
![image](https://github.com/snoww/loa-logs/assets/71574877/f11bafc8-2441-464d-ad35-c83d2c300ab0)
![image](https://github.com/snoww/loa-logs/assets/71574877/4e86f6bf-e2a1-4893-bf17-b2d7873160e4)

**Comment by snoww** [comment]
you opened meter too late. have it open before loading into the raid
