### ISSUE TITLE
Meter not recording

### ISSUE THREAD

**Issue by bigshlong30inches** [snoww/loa-logs#42]
i run lost ark with Exitlag.

the meter recently stopped recording anything, when play without exitlag it works...

is there any way to resolve this with exitlag running at the same time as well?

**Comment by snoww** [comment]
did you do this?

https://github.com/snoww/loa-logs#:~:text=Q%3A%20ExitLag%20not%20working%20even%20with%20the%20settings%20above

**Comment by bigshlong30inches** [comment]
> did you do this?
> 
> https://github.com/snoww/loa-logs#:~:text=Q%3A%20ExitLag%20not%20working%20even%20with%20the%20settings%20above

changing to Legacy - NDIS on exitlag worked, ty!
