### ISSUE TITLE
some weird stuff going on with buffs

### ISSUE THREAD

**Issue by Quiksmage** [snoww/loa-logs#43]
bard buffs don't show up in the buff% or brand
![image](https://github.com/snoww/loa-logs/assets/12449533/82d0c62c-7c99-4e42-bc00-2578ac9e7ffd)

in party synergy view players are missing
![image](https://github.com/snoww/loa-logs/assets/12449533/b99ff27c-ac52-4d4f-94ca-26b4acc17ce1)
![image](https://github.com/snoww/loa-logs/assets/12449533/4b604b4d-16e0-49fb-bf09-336f432b0bc8)

**Comment by snoww** [comment]
was meter opened before loading into the raid? or after loading into the raid

**Comment by Quiksmage** [comment]
you are correct. it appears to be my bad!

**Comment by Quiksmage** [comment]
i was too excited to get the update =P
