### ISSUE TITLE
Feature Request: Filter by local player

### ISSUE THREAD

**Issue by VanStorm** [snoww/loa-logs#45]
Now that we got the feature that we can see our char that we've been playing during a raid it would be nice to be able to filter for it similar to how we can filter for bosses.
I am aware that we can just put in our own name in the search bar for that, but having a filter we could filter by our local char and use the search field to search for a specific player we played with.

**Comment by yamiM0NSTER** [comment]
I believe this idea is possible since #60 was merged. It should be live since 1.5.8 version

You would write your char name and whoever you are looking for

**Comment by VanStorm** [comment]
Yeah it's possible since the 1.5.8 version.
