### ISSUE TITLE
Feature Request: Ability to see local player's DPS on the Past Encounters table

### ISSUE THREAD

**Issue by iwllyu** [snoww/loa-logs#50]
Hey again - thanks so much for adding in player total DPS in the player detail view and the dps graph boss HP bar numbers. Also love the recent changes to the past encounters (cleared, difficulty, local player, etc) screen. 

A big motivator for me using this tool is to see my DPS improve with gear/skill over time. What I've been doing is starring my top runs so I can refer back to them (see what I was doing right in my rotation, what comps or supports I was running with were good, etc), but it would be cool if we could see the local player's DPS listed as a top level column. This way I could ex: filter by my akkan g3 clears and see which pull I had a personal record in.

As an extension to this (and obviously this is more complex) would be to allow sorting of the Past Encounters table so I can sort my filtered encounters by local player DPS descending

**Comment by snoww** [comment]
added in 1.4.5
