### ISSUE TITLE
is the meter able to adaption chinese server?

### ISSUE THREAD

**Issue by 1soon** [snoww/loa-logs#51]
in chinese server we can't skills stats so that hard to play this game, we need the meter, help us!

**Comment by snoww** [comment]
not possible unless someone reverse engineers the network packets for the chinese version

**Comment by snoww** [comment]
you need to decompile the game code, and reverse engineer each packet the game uses

**Comment by 1soon** [comment]
> you need to decompile the game code, and reverse engineer each packet the game uses

wow game code? It seems like it's a bit beyond my ability,  Can you help us?

**Comment by snoww** [comment]
no sorry, i have no idea how to do that

**Comment by 1soon** [comment]
> no sorry, i have no idea how to do that

OK, thk u
