### ISSUE TITLE
I randomly disappear from the meter and log in the Party Buffs section

### ISSUE THREAD

**Issue by Ati1707** [snoww/loa-logs#52]
Hi since probably around 2-4months I have this issue that most of the time I'm not shown in the meter and in the log.
This happens on my support bard I didnt check on my dps chars because I dont go to the Party Buffs tab I only check my damage.

Today I noticed while the meter was running that while doing akkan g3 I suddenly disappeared from the Party Buffs tab. I dont remember exactly when it happened maybe it was the 30x transition and I checked the logs after clearing it and I'm completely removed there in party buffs as wellin the logs I am completely removed as well. It might have something to do with the group split in the party buffs. 
Using V1.4.9 on Windows11 64bit winver 22631.2861 and its running on the host machine.
![grafik](https://github.com/snoww/loa-logs/assets/152104750/16a3c280-ca74-4759-866b-f33533f97be2)

Edit: I checked again and now I am sure that it happens because of the group split view. I ran the meter again and at first it was not divided in 2 groups and I was shown in the meter but after couple seconds in the pull it switched to the group view and I was gone again

**Comment by snoww** [comment]
dm me your log file on discord

**Comment by Ati1707** [comment]
I sometimes opened the log inbetween gates while being in the raid maybe that was causing the problem. I will test it again this week. My raids were done last reset when I opened the issue.I also checked the log and there was no warning or anything that would lead to the bug

**Comment by Ati1707** [comment]
Hi me again sadly I can only test it on so many raids but looks like this only happens if I open the meter between gate transitions not when opening the meter before going in the raid from party finder.
