### ISSUE TITLE
incorrect dps data

### ISSUE THREAD

**Issue by ytzyt** [snoww/loa-logs#53]
![image](https://github.com/snoww/loa-logs/assets/9277616/2d2aa018-e87f-48a2-8f8e-3c2b265c4996)
![image](https://github.com/snoww/loa-logs/assets/9277616/79cf4a08-30c3-446e-a2b6-50bc033d0875)

this abnormal bleed dmg while I had no bleed rune
meter was opened before I enter the raid and G1 G3 data seems normal, just G2 the bleed dmg came out from nowhere

**Comment by snoww** [comment]
did you have your character name loaded in g1 logs? if not the meter was not able to load your info in time. opening meter during loading into the raid is already too late.

**Comment by ytzyt** [comment]
> did you have your character name loaded in g1 logs? if not the meter was not able to load your info in time. opening meter during loading into the raid is already too late.

Oh that's why! hmmmm seems my character name was not loaded throughout the raid. I thought it was designed like this
Maybe I'm wrong but I believe last time I used the meter it was showing "You"?

**Comment by snoww** [comment]
yeah “you” just means it doesn’t know who you are. going into chat select and back will fix it
