### ISSUE TITLE
Live meter Support dmg uptime

### ISSUE THREAD

**Issue by acidh0uze97** [snoww/loa-logs#54]
Is there any possible way to add support dmg uptime buff from party buffs to showing this % in Live meter? Same as we have right now like "Support Brand %" etc. This gonna be huge QoL if possible. Might be possible to make another colomn with smth like "Support AP Buff %", idk. 
if possible - BIG, if not - it is what it is

**Comment by yamiM0NSTER** [comment]
Is this feature added in 1.5.6 what you meant?
![image](https://github.com/snoww/loa-logs/assets/22958062/90679cbe-1067-4fc0-8243-0add4fb21a65)
