### ISSUE TITLE
Meeter being bugged for Bleed damage (it shows just bleed damage doing such 15b)

### ISSUE THREAD

**Issue by Takaber** [snoww/loa-logs#55]
Hello, ehmm found a bug idk how to qualifie being honest but sometimes (not always) when i use some skill that has bleed in such case my GL using taunt with bleed rune, it shows in the meeter that im doing 17b of damage and i was like "naa cant be" then i see where it comes that "damage" and just shows "Bleed" and obviously the 17b damaged dealed, and i see that it shows 2 Gunlancers (notify that in that party im the only GL) and shows 1 with the name Gunlancer and the other one obviously with my name.
![Uh](https://github.com/snoww/loa-logs/assets/51917858/339e749f-b27a-48ed-8b79-fd66a9f61ad1)
![BleedBug](https://github.com/snoww/loa-logs/assets/51917858/7419c678-c624-48ef-b21b-82781288adbc)
![Bugbleed](https://github.com/snoww/loa-logs/assets/51917858/00214986-3854-4caa-b95b-59ca1f23826a)

**Comment by Takaber** [comment]
Ohh yeah was G3 AkkanH i was lantern.

**Comment by snoww** [comment]
meter opened too late
