### ISSUE TITLE
Latest update - VPN no longer working

### ISSUE THREAD

**Issue by convoluted** [snoww/loa-logs#6]
Hi, 

I've just updated to the latest version. But it looks like the interface changed with the previous interface mentioning raw socket. Under the new version, I'm unable to get the log working again. 

I have turned off auto network selection and inputted the Port number. I've tried each interface option but to no avail.

Aside from fixing this, is there any way I can roll back to a previous version of the app?

**Comment by snoww** [comment]
what vpn are you using? i am working on a raw socket implementation
you can roll back by installing the old version manually, and choose not to update when the popup shows
https://github.com/snoww/loa-logs/releases/tag/v1.1.19

**Comment by snoww** [comment]
try beta.6 https://github.com/snoww/loa-logs/releases/tag/v1.2.0-beta.6
enable raw socket then restart as admin

**Comment by convoluted** [comment]
New versions are working on exitlag again. Thank you very much!
