### ISSUE TITLE
Meter and logs window hidden launch

### ISSUE THREAD

**Issue by an-onyme** [snoww/loa-logs#67]
Hi, neither the meter nor the logs windows are starting hidden since a few updates (maybe a couple of weeks)

Running without VM or VPN

**Comment by snoww** [comment]
what version are you on
can you share your settings.json file, and the loa_logs_rCurrent.log file (found in the install folder)

@yamiM0NSTER

**Comment by an-onyme** [comment]
Currently on version 1.5.11

[Here for the files](https://drive.google.com/drive/folders/1HpD4DXSdSxGOfdZbp7KyjmiSEMayRqCl?usp=sharing)

**Comment by snoww** [comment]
have you tried turning the setting off, restarting, and turning on, and restarting? not really sure why it isn't remembering

**Comment by an-onyme** [comment]
Restarting with the setting off might have solved the issue!
Previously I just switched it off/on and then restarted  

Thanks
