### ISSUE TITLE
Loa logs doesn't detect anything

### ISSUE THREAD

**Issue by giggin** [snoww/loa-logs#7]
I just installed loa logs after using loa details for quite a while and once I start it nothing gets detected. I tried uninstalling both loa details and loa logs and noticed that when I try to install loa logs I get this error
![image](https://github.com/snoww/loa-logs/assets/46052932/705846cf-bb6d-40e3-85a4-15a0506bee43)
I'm trying to install it on a VM and it happens even right after booting the VM

**Comment by snoww** [comment]
what version are you installing?

**Comment by giggin** [comment]
I tried installing both 1.19 and beta 1.20 and no I'm not using any VPN

**Comment by snoww** [comment]
check task manager to check if there are any leftover processes running, (loa logs, or node.js javascript runtime)

**Comment by giggin** [comment]
solved. if you happen to have the same issue as me (loa logs not logging anything) you have to open it at the server selection screen. if you open any later it won't log
