### ISSUE TITLE
Fate of the Lazeniths Card Set Tracker

### ISSUE THREAD

**Issue by ManagerWoW** [snoww/loa-logs#71]
A tracker for the Fate of the Lazeniths card set would be very helpful for Strikers/Wardancers. It's a 32 second cooldown that starts as soon as the buff is applied. Even if it's very barebones, just a timer in the title bar that ticks from 32-0 every proc would be awesome.

https://lostarkcodex.com/us/cardset/1032
Buff name: The Lazeniths' Fate

**Comment by snoww** [comment]
i'm gonna have to say that this feature would be out of the scope of what a dps meter can and should do.
