### ISSUE TITLE
Missing bard brand (+ elixir set?)

### ISSUE THREAD

**Issue by Llu90** [snoww/loa-logs#75]
Hi, I use Stigma as secondary brand, but only sound shock appears in the meter (yes I use the right tripod and all).
![image](https://github.com/snoww/loa-logs/assets/14967140/d3ba902c-1581-4f02-bf47-c15f84f37a71)

Also, I have elixir 40 faith, but I noticed it doesn't appear on party buffs tab, but only on the self buffs tab, and only on myself. Would there be a way to see the effective effect of it?
![image](https://github.com/snoww/loa-logs/assets/14967140/e6d60390-2c9f-4298-8e91-14c8fdb9b2a5)
![image](https://github.com/snoww/loa-logs/assets/14967140/25f3cddd-1ff4-4a00-9d73-68e99a2ee29f)

Thank you!

**Comment by snoww** [comment]
hi,
the game categorizes a couple of bard brands as the same brand internally, so we have no way of differentiating in the meter. e.g. ss, note bundle, stigma, harp

it is because faith is only a buff on you, which will not show on other players
