### ISSUE TITLE
[Feature Request] Ability to modify "local player" value for each encounter

### ISSUE THREAD

**Issue by adrianjw** [snoww/loa-logs#76]
The "local player" value sometimes shows a randomly generated hex value instead of actual character name when I open the meter too late (already in the raid).

Can you add a feature that allows us to modify that value afterwards (link it back to a character in the local_players.json) so that these encounters would show up again when searching based on character name?

Thanks.

![Screenshot 2024-03-25 070238](https://github.com/snoww/loa-logs/assets/55360387/b5cf8070-93b8-4176-ac52-46a49aad1089)

**Comment by snoww** [comment]
you should open meter before the raid for character names to load properly.

i do not intend for encounters to be modified.
