### ISSUE TITLE
Shortcuts issue

### ISSUE THREAD

**Issue by AKKUNSAMA** [snoww/loa-logs#77]
All shortcuts doesn't work except for show logs and show meter...
I wanted to make a shortcut for clickthrough and it didn't work
Also I wanted a pause session shortcut and I assigned the key but it doesn't work.. 

How can I fix it?

**Comment by snoww** [comment]
can you upload ur settings.json file

**Comment by AKKUNSAMA** [comment]
[settings.json](https://github.com/snoww/loa-logs/files/14776124/settings.json)

**Comment by snoww** [comment]
hmm not sure, have u tried running as admin? or is there another program using these binds already?
