### ISSUE TITLE
Quality of life feature to be added

### ISSUE THREAD

**Issue by xDido** [snoww/loa-logs#81]
Can you just add app start minimized on windows startup as a feature? every time I open my computer I forget to open the app up and I want my raids to be recorded.
I have tried to do that with a batch file however so far I have only got that the app open but I can't automatically minimize it using the batch file I have to manually press CLOSE.
Thanks in advance,

**Comment by adrianjw** [comment]
![image](https://github.com/snoww/loa-logs/assets/55360387/133d662c-3073-4752-bbce-c6a37925f2cf)
have you tried checking these 2 options?

**Comment by xDido** [comment]
Yes I know how about it starts on windows startup

**Comment by xDido** [comment]
The feature has been added on the 8/5/2024 release. Thanks for your consideration :D
start on Windows startup
