### ISSUE TITLE
Classes images issue

### ISSUE THREAD

**Issue by AKKUNSAMA** [snoww/loa-logs#85]
I cant see any class images.. Idk why 
I have the database folder and I have the classes images in it like normal it just doesn't load in app.. any help with that?

**Comment by AKKUNSAMA** [comment]
![image_2024-04-19_153135486](https://github.com/snoww/loa-logs/assets/165093829/5c38a667-48bc-4953-abe7-8d61721f0d0f)

**Comment by AKKUNSAMA** [comment]
that's how it looks like

**Comment by AKKUNSAMA** [comment]
![image_2024-04-19_153219132](https://github.com/snoww/loa-logs/assets/165093829/33ff07e9-da46-4895-9bb1-0b74860d217f)

**Comment by AKKUNSAMA** [comment]
and thats how the it looks like in live meter

**Comment by snoww** [comment]
where did you install the meter?

**Comment by AKKUNSAMA** [comment]
in the default place I didn't change anything 
C:\Users\Akkun\AppData\Local\LOA Logs

**Comment by snoww** [comment]
hmm im not exactly sure what the reason could be. try running as admin? try reinstalling edge webview2? maybe some antivirus is blocking the images?

**Comment by yellowyao** [comment]
me too
![Uploading image.png…]()

**Comment by yellowyao** [comment]
me too.

**Comment by yellowyao** [comment]
i'm win11,and install in F:\software\laoLogs,runing as admin,reinstalling edge webview2，None of them work

**Comment by snoww** [comment]
apologies for the delay, sorry for all the inconveniences 

the bug will be fixed in 1.9.8
