### ISSUE TITLE
Clicktrough the meter feature

### ISSUE THREAD

**Issue by DoGi114** [snoww/loa-logs#9]
if you could make this happen it would be great !

**Comment by snoww** [comment]
I will look into it, no promises tho

**Comment by snoww** [comment]
how would you like the feature to behave?
once clickthrough is enabled, how would you want to regain access to the window? through keyboard shortcut? cus once you enable it you cant click on the window anymore.

**Comment by DoGi114** [comment]
shortcut would be fine or regaining focus on it via clicking in on windows taskbar idm either way to regain it as long as im not able to click it by accident midmechanic

**Comment by snoww** [comment]
added in v1.2.2
https://github.com/snoww/loa-logs/releases/tag/v1.2.2
