### ISSUE TITLE
Idea for HP Split/Abbreviations

### ISSUE THREAD

**Issue by Rewire2k** [snoww/loa-logs#90]
Seeing how you can divide the Boss' HP bar and showing it on the DPS Meter, it made me think if you could add a per Boss algorithm where the splits occur depending on the Boss' mechanic HP thresholds. This is more of an enhancement but I couldn't find labeling for it, I apologize for that.

**Comment by snoww** [comment]
this would be too much work to maintain, and bosses can sometimes phase early or late depending on patterns
also it wouldnt work on dynamic phases for bosses that do have them
