### ISSUE TITLE
Logs not showing my buff% 

### ISSUE THREAD

**Issue by shibiri1** [snoww/loa-logs#98]
since the last update, my meter won't show my buffs uptime% when I check both party buffs on live meter and logs, my name won't even appear on the list. it only happens when I'm on my paladin.

![imagem_2024-05-21_153054127](https://github.com/snoww/loa-logs/assets/170465611/92c8a7ff-51fb-42c2-8b29-836ed2ad7b22)

**Comment by snoww** [comment]
yes please open meter before you enter a raid
